from yacs.config import CfgNode as CN


_C = CN()

_C.VERSION = 1


_C.OUTPUT_DIR = "./output"

_C.RESUME = ""

_C.SEED = -1
_C.USE_CUDA = True

_C.VERBOSE = True


_C.INPUT = CN()

_C.INPUT.SIZE = (32, 32)

_C.INPUT.INTERPOLATION = "bilinear"

_C.INPUT.TRANSFORMS = ()

_C.INPUT.NO_TRANSFORM = False

_C.INPUT.PIXEL_MEAN = [0.5071, 0.4865, 0.4409]
_C.INPUT.PIXEL_STD = [0.2673, 0.2564, 0.2762]

_C.INPUT.CROP_PADDING = 4

_C.INPUT.RRCROP_SCALE = (0.08, 1.0)

_C.INPUT.CUTOUT_N = 1
_C.INPUT.CUTOUT_LEN = 16

_C.INPUT.GN_MEAN = 0.0
_C.INPUT.GN_STD = 0.15

_C.INPUT.RANDAUGMENT_N = 2
_C.INPUT.RANDAUGMENT_M = 10

_C.INPUT.COLORJITTER_B = 0.4
_C.INPUT.COLORJITTER_C = 0.4
_C.INPUT.COLORJITTER_S = 0.4
_C.INPUT.COLORJITTER_H = 0.1

_C.INPUT.RGS_P = 0.2
# Gaussian blur
_C.INPUT.GB_P = 0.5  
_C.INPUT.GB_K = 21 


_C.DATASET = CN()

_C.DATASET.ROOT = ""
_C.DATASET.NAME = ""

_C.DATASET.SOURCE_DOMAINS = ()
_C.DATASET.TARGET_DOMAINS = ()

_C.DATASET.NUM_LABELED = -1

_C.DATASET.NUM_SHOTS = 2

_C.DATASET.VAL_PERCENT = 0.1

_C.DATASET.STL10_FOLD = -1

_C.DATASET.CIFAR_C_TYPE = ""
_C.DATASET.CIFAR_C_LEVEL = 1

_C.DATASET.ALL_AS_UNLABELED = False


_C.DATALOADER = CN()
_C.DATALOADER.NUM_WORKERS = 4

_C.DATALOADER.K_TRANSFORMS = 1

_C.DATALOADER.RETURN_IMG0 = False

_C.DATALOADER.TRAIN_X = CN()
_C.DATALOADER.TRAIN_X.SAMPLER = "RandomSampler"
_C.DATALOADER.TRAIN_X.BATCH_SIZE = 32

_C.DATALOADER.TRAIN_X.N_DOMAIN = 0

_C.DATALOADER.TRAIN_X.N_INS = 16


_C.DATALOADER.TRAIN_U = CN()

_C.DATALOADER.TRAIN_U.SAME_AS_X = True
_C.DATALOADER.TRAIN_U.SAMPLER = "RandomSampler"
_C.DATALOADER.TRAIN_U.BATCH_SIZE = 32
_C.DATALOADER.TRAIN_U.N_DOMAIN = 0
_C.DATALOADER.TRAIN_U.N_INS = 16


_C.DATALOADER.TEST = CN()
_C.DATALOADER.TEST.SAMPLER = "SequentialSampler"
_C.DATALOADER.TEST.BATCH_SIZE = 32


_C.MODEL = CN()

_C.MODEL.INIT_WEIGHTS = ""
_C.MODEL.BACKBONE = CN()
_C.MODEL.BACKBONE.NAME = ""
_C.MODEL.BACKBONE.PRETRAINED = True

_C.MODEL.HEAD = CN()

_C.MODEL.HEAD.NAME = ""

_C.MODEL.HEAD.HIDDEN_LAYERS = ()
_C.MODEL.HEAD.ACTIVATION = "relu"
_C.MODEL.HEAD.BN = True
_C.MODEL.HEAD.DROPOUT = 0.0


_C.OPTIM = CN()
_C.OPTIM.NAME = "adam"
_C.OPTIM.LR = 0.0003
_C.OPTIM.WEIGHT_DECAY = 5e-4
_C.OPTIM.MOMENTUM = 0.9
_C.OPTIM.SGD_DAMPNING = 0
_C.OPTIM.SGD_NESTEROV = False
_C.OPTIM.RMSPROP_ALPHA = 0.99

_C.OPTIM.ADAM_BETA1 = 0.9
_C.OPTIM.ADAM_BETA2 = 0.999

_C.OPTIM.STAGED_LR = False
_C.OPTIM.NEW_LAYERS = ()
_C.OPTIM.BASE_LR_MULT = 0.1

_C.OPTIM.LR_SCHEDULER = "single_step"

_C.OPTIM.STEPSIZE = (-1, )
_C.OPTIM.GAMMA = 0.1
_C.OPTIM.MAX_EPOCH = 1

_C.OPTIM.WARMUP_EPOCH = -1

_C.OPTIM.WARMUP_TYPE = "linear"

_C.OPTIM.WARMUP_CONS_LR = 1e-5

_C.OPTIM.WARMUP_MIN_LR = 1e-5

_C.OPTIM.WARMUP_RECOUNT = True


_C.TRAIN = CN()

_C.TRAIN.CHECKPOINT_FREQ = 0

_C.TRAIN.PRINT_FREQ = 10

_C.TRAIN.COUNT_ITER = "train_x"


_C.TEST = CN()
_C.TEST.EVALUATOR = "Classification"
_C.TEST.PER_CLASS_RESULT = False

_C.TEST.COMPUTE_CMAT = False

_C.TEST.NO_TEST = False

_C.TEST.SPLIT = "test"

_C.TEST.FINAL_MODEL = "last_step"


_C.TRAINER = CN()
_C.TRAINER.NAME = ""


_C.TRAINER.MCD = CN()
_C.TRAINER.MCD.N_STEP_F = 4 

_C.TRAINER.MME = CN()
_C.TRAINER.MME.LMDA = 0.1  

_C.TRAINER.CDAC = CN()
_C.TRAINER.CDAC.CLASS_LR_MULTI = 10
_C.TRAINER.CDAC.RAMPUP_COEF = 30
_C.TRAINER.CDAC.RAMPUP_ITRS = 1000
_C.TRAINER.CDAC.TOPK_MATCH = 5
_C.TRAINER.CDAC.P_THRESH = 0.95
_C.TRAINER.CDAC.STRONG_TRANSFORMS = ()

_C.TRAINER.SE = CN()
_C.TRAINER.SE.EMA_ALPHA = 0.999
_C.TRAINER.SE.CONF_THRE = 0.95
_C.TRAINER.SE.RAMPUP = 300

_C.TRAINER.M3SDA = CN()
_C.TRAINER.M3SDA.LMDA = 0.5 
_C.TRAINER.M3SDA.N_STEP_F = 4  

_C.TRAINER.DAEL = CN()
_C.TRAINER.DAEL.WEIGHT_U = 0.5  
_C.TRAINER.DAEL.CONF_THRE = 0.95  
_C.TRAINER.DAEL.STRONG_TRANSFORMS = ()


_C.TRAINER.CROSSGRAD = CN()
_C.TRAINER.CROSSGRAD.EPS_F = 1.0  
_C.TRAINER.CROSSGRAD.EPS_D = 1.0  
_C.TRAINER.CROSSGRAD.ALPHA_F = 0.5  
_C.TRAINER.CROSSGRAD.ALPHA_D = 0.5 

_C.TRAINER.DDAIG = CN()
_C.TRAINER.DDAIG.G_ARCH = "" 
_C.TRAINER.DDAIG.LMDA = 0.3  
_C.TRAINER.DDAIG.CLAMP = False 
_C.TRAINER.DDAIG.CLAMP_MIN = -1.0
_C.TRAINER.DDAIG.CLAMP_MAX = 1.0
_C.TRAINER.DDAIG.WARMUP = 0
_C.TRAINER.DDAIG.ALPHA = 0.5  

_C.TRAINER.DAELDG = CN()
_C.TRAINER.DAELDG.WEIGHT_U = 0.5 
_C.TRAINER.DAELDG.CONF_THRE = 0.95  
_C.TRAINER.DAELDG.STRONG_TRANSFORMS = ()

_C.TRAINER.DOMAINMIX = CN()
_C.TRAINER.DOMAINMIX.TYPE = "crossdomain"
_C.TRAINER.DOMAINMIX.ALPHA = 1.0
_C.TRAINER.DOMAINMIX.BETA = 1.0


_C.TRAINER.ENTMIN = CN()
_C.TRAINER.ENTMIN.LMDA = 1e-3  

_C.TRAINER.MEANTEACHER = CN()
_C.TRAINER.MEANTEACHER.WEIGHT_U = 1.0  
_C.TRAINER.MEANTEACHER.EMA_ALPHA = 0.999
_C.TRAINER.MEANTEACHER.RAMPUP = 5  

_C.TRAINER.MIXMATCH = CN()
_C.TRAINER.MIXMATCH.WEIGHT_U = 100.0  
_C.TRAINER.MIXMATCH.TEMP = 2.0  
_C.TRAINER.MIXMATCH.MIXUP_BETA = 0.75
_C.TRAINER.MIXMATCH.RAMPUP = 20000  

_C.TRAINER.FIXMATCH = CN()
_C.TRAINER.FIXMATCH.WEIGHT_U = 1.0 
_C.TRAINER.FIXMATCH.CONF_THRE = 0.95  
_C.TRAINER.FIXMATCH.STRONG_TRANSFORMS = ()
